fix(package.json): pin @types/enzyme to 3.1.17 (#1144)
extinguish the fire, 3.1.18 fails build and the chain afterwards
```
node_modules/@types/enzyme/index.d.ts(60,20): error TS2314: Generic type 'ReactElement<P>' requires 1 type argument(s).
```